Empty compose
WebThingsIO/android-app pull request #40
Opened 2022-04-21 00:05 UTC by arist0v

Initial empty compose project

2022-04-21 11:15 UTC, benfrancis reviewed
It's a few years since I created an empty Android project so I'm not really sure what most of this boilerplate configuration is for, so the only helpful feedback I have is on naming 😆

Please note that the name of the project should be capitalised as "WebThings", not "Webthings".

Regarding the java namespace, `io.webthings.webthings` is a bit confusing because of the repetition and the potential for confusion with the `io.webthings.webthing` namespace used by the [webthing-java](https://github.com/WebThingsIO/webthing-java) library. Would `io.webthings.app` make more sense? @tim-hellhake what do you think?

2022-04-21 12:25 UTC, arist0v commented
i agree to move it to app instead of second webthings, for now the major part of those file isn't OK since it was the default android compose project settings, i will adapt the file in the next PR i will do

2022-04-23 17:37 UTC, tim-hellhake requested changes
The `.idea` folder shouldn't be committed to the repo.
Please add it to `.gitignore` and remove the it.

2022-04-23 17:38 UTC, tim-hellhake commented
> Would `io.webthings.app` make more sense? @tim-hellhake what do you think?

I agree.

2022-04-23 17:52 UTC, arist0v commented
> > Would `io.webthings.app` make more sense? @tim-hellhake what do you think?
> 
> I agree.

This will be changed in #49

2022-04-23 17:54 UTC, tim-hellhake commented
I would prefer to change it here.
Otherwise, it will add a lot of noise to other PRs.

2022-04-23 18:03 UTC, tim-hellhake requested changes

2022-04-23 18:03 UTC, tim-hellhake commented on .gitignore
>  .idea/gradle.xml
Those are no longer needed.
```suggestion
```

2022-04-23 18:06 UTC, tim-hellhake requested changes
Please change the namespace to `io.webthings.app` then we can merge it.

2022-04-23 18:08 UTC, arist0v commented
done

2022-04-23 18:09 UTC, tim-hellhake commented
@arist0v You don't need to replicate the changes in the other PRs.
As soon this is merged you can rebase the other branches.

2022-04-23 18:11 UTC, tim-hellhake requested changes

2022-04-23 18:11 UTC, tim-hellhake commented on app/src/androidTest/java/io/webthings/app/ExampleInstrumentedTest.kt
> +        assertEquals("io.webthings.webthings", appContext.packageName)
```suggestion
        assertEquals("io.webthings.app", appContext.packageName)
```

2022-04-23 18:11 UTC, tim-hellhake commented on app/build.gradle
> +        applicationId "io.webthings.webthings"
```suggestion
        applicationId "io.webthings.app"
```

2022-04-23 18:12 UTC, arist0v commented
> @arist0v You don't need to replicate the changes in the other PRs. As soon this is merged you can rebase the other branches.

yeah i knew, but i never done that and was kind of lazy googling :P

2022-04-23 18:20 UTC, arist0v commented
should be good to go now

2022-04-23 20:03 UTC, tim-hellhake approved these changes
Just installed it on my phone and everything seems to be fine.

2022-04-23 20:08 UTC, merged